In [1]:
#Download the necessary libraries

import os, os.path
import cv2 # important : import Open CV
import numpy as np # Import numpy library 
from sklearn.model_selection import StratifiedKFold #Import stratified kfold as we are using a 10fold cross validation approach
from sklearn.svm import LinearSVC # Import the Linear SVM Classifier
from skimage.feature import hog # Import Hog model to extract features
from sklearn.metrics import confusion_matrix # Import confusion matrix to evaluate the performance

# create the necessary empty lists
imgs = []
y=[]
file_size = []
k=0
path = "./data/101_ObjectCategories" # Give the dataset path here



In [2]:
folder = os.listdir(path) # from the given path get the file names such as accordion, airplanes etc..
for file in folder: # for every file name in the given path go inseide that directory and get the images
    subpath = os.path.join(path,file)  # Join the name of these files to the previous path 
    
    files = os.listdir(subpath) # Take these image names to a list called files
    j=0
    for i in range(np.size(files)): # now we shall loop through these number of files
        
        im=cv2.imread(subpath+'/'+files[0+j]) # Read the images from this subpath
        
        imgs.append(im) # append all the read images to a list called imgs
        y.append(k) # generate a labe to every file and append it to y

        j+=1
        if (j == (np.size(files))):
            file_size.append(j)
   
    k+=1
     
y=np.array(y).tolist()

ix=[]
for index, item in enumerate(imgs):
    if (np.size(item) == 1):
        ix.append(index)
        del imgs[index]
        
for index, item in enumerate(y):
    for v in range(np.size(ix)):
        if (index == ix[v]):
            del y[index]
        
y=np.array(y).astype(np.float64) 

# Function to convert an image from color to grayscale
def rgb2gray(rgb):
    gray = cv2.cvtColor(rgb, cv2.COLOR_BGR2GRAY)
    return gray

def resize_(image):
    u=cv2.resize(image,(256,256))
    return u

def fd_hog(image):
    fd, hog_image = hog(image, orientations=8, pixels_per_cell=(64, 64),
                    cells_per_block=(1, 1), visualise=True)
    
    return fd

a=[]

for img in imgs:
    
    b=resize_(img)
    c=rgb2gray(b)   
    d=fd_hog(c)
    a.append(d)

a=np.array(a)

score = []
skf = StratifiedKFold(n_splits = 10) # divide the complete dataset in to 10 folds
skf.get_n_splits(a, y)

accuracy = 0    

/Users/rsong/opt/anaconda3/lib/python3.7/site-packages/skimage/feature/_hog.py:239: skimage_deprecation: Argument `visualise` is deprecated and will be changed to `visualize` in v0.16
  'be changed to `visualize` in v0.16', skimage_deprecation)


In [3]:
for train_index, test_index in skf.split(a,y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = a[train_index], a[test_index]
    y_train, y_test = y[train_index], y[test_index] 


    clf = LinearSVC(random_state=0)
    
    clf.fit(X_train, y_train)
        
    y_pred = clf.predict(X_test)
    
    scr = clf.score(X_test, y_test)
    print(scr)
    score.append(scr)
    accuracy += scr
    cnf_matrix = confusion_matrix(y_test, y_pred)
    print(cnf_matrix)

score = np.array(score)

fin_accuracy = (accuracy/10)*100

print("Final Accuracy is: {}".format(fin_accuracy))

TRAIN: [   4    5    6 ... 9142 9143 9144] TEST: [   0    1    2    3   34   35   36   37   38   39   40   41   42   43
  134  135  136  137  138  176  177  178  179  180  218  219  220  221
  222  223  224  225  226  227  309  310  311  312  313  314  315  370
  371  372  373  405  406  407  408  442  443  444  445  446  447  448
  449  450  451  452  549  550  551  552  553  554  555  617  618  619
  620  621  622  623  624  690  691  692  693  694  737  738  739  740
  741  742  789  790  791  792  793  794  842  843  844  845  873  874
  875  876  907  908  909  910  911  912  913  974  975  976  977  978
  979 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043
 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057
 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071
 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1085
 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098 1099
 1100 1101 1102 1103 1104 11

0.4616193480546793
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
TRAIN: [   0    1    2 ... 9142 9143 9144] TEST: [   8    9   10   11   54   55   56   57   58   59   60   61   62   63
  144  145  146  147  186  187  188  189  237  238  239  240  241  242
  243  244  245  322  323  324  325  326  327  378  379  380  381  413
  414  415  416  464  465  466  467  468  469  470  471  472  473  474
  563  564  565  566  567  568  569  633  634  635  636  637  638  639
  640  700  701  702  703  704  749  750  751  752  753  801  802  803
  804  805  806  849  850  851  881  882  883  884  921  922  923  924
  925  926  927  986  987  988  989  990  991 1191 1192 1193 1194 1195
 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209
 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223
 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237
 1238 1239 1240 1241 1242 1243 

0.46737967914438505
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
TRAIN: [   0    1    2 ... 9142 9143 9144] TEST: [  16   17   18   74   75   76   77   78   79   80   81   82   83  152
  153  154  155  194  195  196  197  255  256  257  258  259  260  261
  262  263  334  335  336  337  338  339  386  387  388  389  421  422
  423  424  486  487  488  489  490  491  492  493  494  495  496  577
  578  579  580  581  582  583  648  649  650  651  652  653  654  710
  711  712  713  714  759  760  761  762  763  812  813  814  815  816
  855  856  857  889  890  891  935  936  937  938  939  940  941  998
  999 1000 1001 1002 1003 1351 1352 1353 1354 1355 1356 1357 1358 1359
 1360 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370 1371 1372 1373
 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385 1386 1387
 1388 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401
 1402 1403 1404 1405 1406 1407

0.4613686534216336
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
TRAIN: [   0    1    2 ... 9142 9143 9144] TEST: [  22   23   24   94   95   96   97   98   99  100  101  102  103  160
  161  162  163  202  203  204  205  273  274  275  276  277  278  279
  280  281  346  347  348  349  350  351  393  394  395  429  430  431
  432  508  509  510  511  512  513  514  515  516  517  518  591  592
  593  594  595  596  597  662  663  664  665  666  667  668  720  721
  722  723  724  769  770  771  772  773  822  823  824  825  826  861
  862  863  895  896  897  949  950  951  952  953  954  955 1010 1011
 1012 1013 1014 1015 1511 1512 1513 1514 1515 1516 1517 1518 1519 1520
 1521 1522 1523 1524 1525 1526 1527 1528 1529 1530 1531 1532 1533 1534
 1535 1536 1537 1538 1539 1540 1541 1542 1543 1544 1545 1546 1547 1548
 1549 1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560 1561 1562
 1563 1564 1565 1566 1567 1568 

0.463882618510158
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 1]
 ...
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]
TRAIN: [   0    1    2 ... 9142 9143 9144] TEST: [  28   29   30  114  115  116  117  118  119  120  121  122  123  168
  169  170  171  210  211  212  213  291  292  293  294  295  296  297
  298  299  358  359  360  361  362  363  399  400  401  436  437  438
  529  530  531  532  533  534  535  536  537  538  605  606  607  608
  609  610  676  677  678  679  680  681  682  729  730  731  732  779
  780  781  782  783  832  833  834  835  836  867  868  869  901  902
  903  962  963  964  965  966  967 1021 1022 1023 1024 1025 1671 1672
 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682 1683 1684 1685 1686
 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696 1697 1698 1699 1700
 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710 1711 1712 1713 1714
 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724 1725 1726 1727 1728
 1729 1730 1731 1732 1733 1734 1

0.4815242494226328
[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 2]]
Final Accuracy is: 46.8916783962514


In [4]:
from hashlib import sha1
import numpy as np
from datasketch.minhash import MinHash
from datasketch.weighted_minhash import WeightedMinHashGenerator
from datasketch.lsh import MinHashLSH

In [5]:
from platform import python_version
print(python_version())

3.7.4


In [6]:
set1 = set(['minhash', 'is', 'a', 'probabilistic', 'data', 'structure', 'for',
            'estimating', 'the', 'similarity', 'between', 'datasets'])
set2 = set(['minhash', 'is', 'a', 'probability', 'data', 'structure', 'for',
            'estimating', 'the', 'similarity', 'between', 'documents'])
set3 = set(['minhash', 'is', 'probability', 'data', 'structure', 'for',
            'estimating', 'the', 'similarity', 'between', 'documents'])

In [7]:
v1 = np.random.uniform(1, 10, 10)
v2 = np.random.uniform(1, 10, 10)
v3 = np.random.uniform(1, 10, 10)

In [8]:
def eg1():
    m1 = MinHash(num_perm=128)
    m2 = MinHash(num_perm=128)
    m3 = MinHash(num_perm=128)
    for d in set1:
        m1.update(d.encode('utf8'))
    for d in set2:
        m2.update(d.encode('utf8'))
    for d in set3:
        m3.update(d.encode('utf8'))

    # Create LSH index
    lsh = MinHashLSH(threshold=0.5, num_perm=128)
    lsh.insert("m2", m2)
    lsh.insert("m3", m3)
    result = lsh.query(m1)
    print("Approximate neighbours with Jaccard similarity > 0.5", result)

In [9]:
def eg2():
    mg = WeightedMinHashGenerator(10, 5)
    m1 = mg.minhash(v1)
    m2 = mg.minhash(v2)
    m3 = mg.minhash(v3)
    print("Estimated Jaccard m1, m2", m1.jaccard(m2))
    print("Estimated Jaccard m1, m3", m1.jaccard(m3))
    # Create LSH index
    lsh = MinHashLSH(threshold=0.1, num_perm=5)
    lsh.insert("m2", m2)
    lsh.insert("m3", m3)
    result = lsh.query(m1)
    print("Approximate neighbours with weighted Jaccard similarity > 0.1", result)

In [10]:
if __name__ == "__main__":
    eg1()
    eg2()

Approximate neighbours with Jaccard similarity > 0.5 ['m3', 'm2']
Estimated Jaccard m1, m2 0.4
Estimated Jaccard m1, m3 0.8
Approximate neighbours with weighted Jaccard similarity > 0.1 ['m3', 'm2']


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(a, y, test_size=0.3)

In [13]:
lit = []
for i in range(len(X_train)):
    curr = X_train[i].astype(str)
    lit.append(curr)

In [16]:
len(lit)

6401

In [25]:
lit

[array(['0.4236572750862897', '0.4236572750862897', '0.28768638899217924',
        '0.3591329396571826', '0.4236572750862897', '0.17727105869031126',
        '0.19721333020303888', '0.4236572750862897', '0.38957908181740236',
        '0.21231751474570118', '0.32535258773220027',
        '0.36572809233347126', '0.38957908181740236',
        '0.38957908181740236', '0.38957908181740236', '0.328971860085477',
        '0.3162446702753744', '0.2759272548806748', '0.46751044609091674',
        '0.46751044609091674', '0.46751044609091674',
        '0.30172084054728654', '0.22656090346776175',
        '0.16059295680989993', '0.3663777063744042', '0.2948057268353891',
        '0.33933062651809337', '0.3663777063744042', '0.3663777063744042',
        '0.3560634639435348', '0.3663777063744042', '0.3663777063744042',
        '0.42197884457435453', '0.2994365181630898', '0.285870823067886',
        '0.22342517150080107', '0.2974259891968526', '0.39501415360576503',
        '0.42197884457435453', '0.

In [26]:
mlist = []
m = MinHash(num_perm=128)
for i in range(len(lit)):
        mlist.append(m)

AttributeError: 'numpy.float64' object has no attribute 'encode'